pipeline:
    test:
        image: node:7.5.0
        commands:
            - npm install -q
            - npm run lint -q
        when:
            branch: master
            event: [push, pull_request, deployment]
    package:
        image: node:7.5.0
        commands:
            - npm install -q
            - npm run lint -q
            - npm run pack -q
        when:
            event: tag
    publish:
        image: plugins/npm
        folder: dist
        when:
            event: tag